package college.leave.Model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents a Department entity in the system.
 * This entity is mapped to a database table and stores department-related
 * information.
 */
@Entity
@Data

@Table(name = "Departments")
public class DeptEntity {

    /**
     * Unique identifier for the department.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer deptId;

    /**
     * Name of the department.
     */
    private String deptName;
    private Integer HODId;
}
