package college.leave.Model;

import college.leave.Model.Enums.ApprovalStatus;
import college.leave.Model.Enums.LeaveType;
import jakarta.persistence.*;
import lombok.Data;

import java.util.Date;

/**
 * Represents a Leave Application entity in the system.
 * This entity is mapped to a database table and stores information about leave
 * applications.
 */
@Entity
@Data
public class LeaveApplicationEntity {

    /**
     * Unique identifier for the leave application.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long leaveId;

    /**
     * The student who applied for the leave.
     * Mapped to the StudentsEntity table.
     */
    @OneToMany
    @JoinColumn(name = "studentId")
    private StudentsEntity studentId;

    /**
     * The start date of the leave.
     */
    private Date fromDate;

    /**
     * The end date of the leave.
     */
    private Date toDate;

    /**
     * The reason for the leave application.
     */
    private String reason;

    /**
     * The date when the leave application was submitted.
     */
    private Date appliedDate;

    /**
     * The current approval status of the leave application.
     * Defaults to PENDING.
     */
    private ApprovalStatus status = ApprovalStatus.PENDING;

    /**
     * The mentor responsible for reviewing the leave application.
     * Mapped to the MentorEntity table.
     */
    @OneToMany
    @JoinColumn(name = "mentorID")
    private MentorEntity mentor;

    /**
     * The type of leave being applied for.
     * Defaults to CASUAL_LEAVE.
     */
    private LeaveType leaveType = LeaveType.CASUAL_LEAVE;

    /**
     * The URL of the document uploaded as proof or supporting material for the
     * leave.
     * This field is optional.
     */
    @Column(nullable = true)
    private String docUrl;
}
