package college.leave.Model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents a Mentor entity in the system.
 * This entity is mapped to a database table and stores mentor-related
 * information.
 */
@Entity
@Data
@Table(name = "MentorDetails")
public class MentorEntity {

    /**
     * Unique identifier for the mentor.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long mentorId;

    /**
     * Name of the faculty member.
     */
    private String facultyName;

    /**
     * Unique email address of the mentor.
     */
    @Column(unique = true)
    private String email;

    @ManyToOne
    @JoinColumn(name = "deptId")
    private DeptEntity deptId;
    /**
     * Password for the mentor's account.
     */
    private String password;

    /**
     * Unique phone number of the mentor.
     */
    @Column(unique = true)
    private Long phoneNumber;
}
