package college.leave.Model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents a Mentor entity in the system.
 * This entity is mapped to a database table and stores mentor-related
 * information.
 */
@Entity
@Data
@Table(name="Mentors")
public class MentorEntity {

    /**
     * Unique identifier for the mentor.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String mentorId;

    /**
     * Name of the faculty member.
     */
    private String facultyName;

    /**
     * Unique email address of the mentor.
     */
    @Column(unique = true)
    private String email;

    /**
     * Password for the mentor's account.
     */
    private String password;

    /**
     * Unique phone number of the mentor.
     */
    @Column(unique = true)
    private Long phoneNumber;
}
