package college.leave.Model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents a Student entity in the system.
 * This entity is mapped to a database table and stores student-related
 * information.
 */
@Entity
@Data
@Table(name = "Students")
public class StudentsEntity {

    /**
     * Unique identifier for the student.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long studentId;

    /**
     * Name of the student.
     */
    private String studentName;

    /**
     * Unique email address of the student.
     */
    @Column(unique = true)
    private String email;

    /**
     * Unique phone number of the student.
     */
    @Column(unique = true)
    private Long phoneNo;

    /**
     * Password for the student's account.
     */
    private String password;

    @OneToMany
    @JoinColumn(name = "deptId")
    private DeptEntity deptId;

    @OneToMany
    @JoinColumn(name = "mentorId")
    private MentorEntity mentorId;
}
